### ISSUE TITLE
Issue while running the "h2o_DLNN.R" script (in R studio)

### ISSUE THREAD

**Issue by soorya97** [kvougas/Vougas_DeepLearning#2]
I am getting the following issues while I run the "**h2o_DLNN.R**" script in the R studio.......

**> result<-dbGetQuery(con,"SELECT Drug,Drug_Status FROM deep_learning_prediction_metrics ORDER BY 
       id DESC LIMIT 1")**
                                          Error in rsqlite_send_query(conn@ptr, statement) : 
                                                                        no such table: deep_learning_prediction_metrics

**P.S : it is on the line number 65......I have done all the pre-requisites stuffs(package and installation).......but this error pops.....please have a look!!!**

**Comment by kvougas** [comment]
I just uploaded an empty SQLite file called ARM_empty.db. Download it, rename it to ARM_dl.db, point the h2o_DLNN.R script to the file [con<-dbConnect(SQLite(),"~/Projects/MBA/new_data/ARM_dl.db")] and it should work.

**Comment by soorya97** [comment]
Oh oki, I will check it out and post the results!!

**Comment by soorya97** [comment]
Nope....unfortunately, even after doing exactly what you told me....the same thing pops up....

Error in rsqlite_send_query(conn@ptr, statement) :
no such table: deep_learning_prediction_metrics

Please have a look at it!!

**Comment by kvougas** [comment]
are you sure you have downloaded ARM_empty.db and renamed it to ARM_dl.db and put it in the correct folder indicated by the script line "con<-dbConnect(SQLite(),"~/YourFolder/ARM_dl.db")"?

**Comment by soorya97** [comment]
Yep....I did the same thing.......what should I do now!!!

**Comment by kvougas** [comment]
can you please send me your ARM_dl.db file as well as the script that you have modified?

**Comment by soorya97** [comment]
Sir, I just re-compiled the code.....and its working fine......thank you for providing the "db" file!!!

It works!!!

**Comment by kvougas** [comment]
Glad it worked!
